version: '3.9'
services:
  server:
    build: ./server
    ports: 
      - "80:5000"
    volumes:
      - ./server:/app
    depends_on:
      - postgres
  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/user/src/app/src
    depends_on:
      - server
  script:
    build: ./scripts
    volumes:
      - ./scripts:/scripts
    depends_on:
      - postgres
    environment:
      - TZ=America/New_York
  postgres:
    image: postgres:10.5
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./postgres/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
