version: '3.9'
services:
  server:
    build: ./server
    ports: 
      - "80:5000"
    volumes:
      - ./server:/app
    environment:
      FLASK_ENV: development
  web:
    build: ./client/react-app
    ports:
      - "3000:3000"
    volumes:
      - ./client/react-app:/user/src/app
    depends_on:
      - server
  postgres:
    image: postgres:10.5
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./postgres/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
